### ISSUE TITLE
CDM fails to start X in latest Archlinux

### ISSUE THREAD

**Issue by rjayasinghe** [evertiro/cdm#32]
Hi!
After my last system upgrade my Archlinux machine fails to open my X session with CDM. As I am not the only user facing this issue (https://bbs.archlinux.org/viewtopic.php?pid=1413023#p1413023) I guess that someone from the CDM maintainers should have a look. The linked forum post describes the observations as well as a change to /usr/bin/cdm-xlaunch which fixes the issue.

Best Regards,
Robin

**Comment by f3bruary** [comment]
The fix doesn't seem to work for me. I use openbox.

**Comment by Seeker14491** [comment]
I don't think this should have been closed; I still had to apply the changes in #33 to fix this issue for me, which hasn't been merged.
