### ISSUE TITLE
cdm disrespects the XDG Base Directory Specification

### ISSUE THREAD

**Issue by kerwindena** [evertiro/cdm#38]
The XDG Base Directory Specification states:

> `$XDG_CONFIG_HOME` defines the base directory relative to which user specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used.
(https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html)

The default is not implemented in cdm: In /src/cdm [Line 68](https://github.com/ghost1227/cdm/blob/master/src/cdm#L68) and [Line 69](https://github.com/ghost1227/cdm/blob/master/src/cdm#L69) `$XDG_CONFIG_HOME` is used without any fallback.

I guess `${XDG_CONFIG_HOME:-$HOME/.config}` should be used instead to respect the specification.

**Comment by evertiro** [comment]
Merged!
